name: Code checks

on:
  push:
    branches:
      - '**'

jobs:
  lint-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/provision

      - name: Lint
        run: yarn lint:prettier

  lint-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/provision

      - name: Lint
        run: yarn lint:eslint

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/provision

      - name: Audit
        run: yarn audit-ci --high --skip-dev

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/provision

      - name: Typecheck
        run: yarn typecheck

  lint-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/provision

      - name: Lint dependency rules
        run: yarn lint:deps

  locked-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/provision

      - name: Check exact versions
        uses: ./.github/actions/check-version-lock

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/provision

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test:unit

  lint-message-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/provision

      - name: Validate message schema
        run: yarn lint:remote-wallet-config

  lint-unused-exports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/provision

      - name: Lint unused TypeScript exports
        run: yarn lint:unused-exports

  lint-firefox-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/provision

      - run: yarn build
        env:
          MINIFY_PRODUCTION_BUILD: true
          TARGET_BROWSER: firefox

      - run: yarn web-ext lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/provision

      - name: Build
        run: yarn build

      - name: Build extension
        run: sh build-ext.sh
        shell: bash
